export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';
export const GET_TOURNAMENT_MATCH_BY_ID = 'GET_TOURNAMENT_MATCH_BY_ID';
export const GET_REWARD_TOURNAMENT = 'GET_REWARD_TOURNAMENT';
export const GET_RULE_OF_AWARD = 'GET_RULE_OF_AWARD';
